[server]
# Configure the server to not use the asyncio event loop
runOnSave = false
headless = true
port = 8501

[browser]
# Disable the server address and port in the browser
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
# Disable the file watcher to avoid the torch.classes error
fileWatcherType = "none"

[client]
# Disable the run on save feature
runOnSave = false
